# Generated by Django 5.2.3 on 2025-12-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
    ]
